---
title: "ciRcus"
author: "Petar Glazar; Vedran Franke"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
  fig_caption: yes
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Introduction

# Installation

# Circ RNA detection

# Summarize detected Circ RNAs

```{r library, eval=FALSE, echo=TRUE}
library(ciRcus)
```


```{r Summarize_Circs, eval=FALSE, echo=TRUE}

circ.files = list.files(sytem.files('extdata'), pattern='bed', full.names=TRUE)

coldata = data.frame(sample = sub('.bed','',basename(circ.files)), 
                     file=circ.files)

circs = summarizeCircs(circ.files)

circs

```

# Annotate Circs
```{r Annotate_Circs, eval=FALSE, echo=TRUE}


circs = AnnotatateCircs(circs)

circs

```



# Explore results

## Sample statistics


## Circ statistics
```{r annotPie, eval=FALSE, echo=TRUE}
histogram(circs)
```


```{r histogram, eval=FALSE, echo=TRUE}
histogram(circs)
```


# Access to CircBase


